source 'https://cdn.cocoapods.org/'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!
platform :ios, '11.0'

# workaround for https://github.com/CocoaPods/CocoaPods/issues/8073
# need for correct invalidate of cache MultiPlatformLibrary.framework
install! 'cocoapods', :disable_input_output_paths => true

target 'TestProj' do
  # MultiPlatformLibrary
  pod 'MultiPlatformLibrary', :path => '../mpp-library'

  pod 'mppLibraryIos', :path => '../mpp-library'
  pod 'moko-widgets-flat', :path => '../../'
  pod 'moko-widgets-bottomsheet', :path => '../../'
  pod 'moko-widgets-collection', :path => '../../'
  pod 'moko-widgets-image-network', :path => '../../'
end
